# Generated by Django 3.2.6 on 2021-08-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='mod1_discord',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='talks',
            name='mod2_discord',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
