# Generated by Django 3.2.6 on 2021-08-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runbook', '0002_auto_20210806_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
