# Generated by Django 3.2.6 on 2021-08-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runbook', '0004_talks_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('mod1_discord', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
