# Generated by Django 3.2.6 on 2021-08-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runbook', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
