# Generated by Django 3.2.6 on 2021-08-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runbook', '0006_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
